### ISSUE TITLE
Need help in task : "Gitcoin: 2) Deploy A Simple Ethereum Smart Contract On Polyjuice"

### ISSUE THREAD

**Issue by deepansharya1111** [haxyz/nervos-hackathon-2021#1]
Hi, can you please help me? I'm stuck at the first step, where we have to replace "Read Function Name" and "Write Function Name" in the index.json file. I couldn't understand where to find these function names, can you guide me, please?

**Comment by haxyz** [comment]
Hi Deepansh, look in the ABI, you'll see 3 methods names: "costructor", "get" and "set". You can exclude the constructor. So one of other two is a "Read Function Name" and the "Write Function Name" and the other a "Write Function Name" 😏

**Comment by haxyz** [comment]
But to get it to work it's tricky: in that "set" you have to specify an amount, say 10, otherwise it'll complain about a missing parameter ;)

**Comment by haxyz** [comment]
Yawn, gonna go to sleep now, good luck!

**Comment by deepansharya1111** [comment]
Thanks, it worked!
